### ISSUE TITLE
0.1.4.0 Hackage version was overwritten

### ISSUE THREAD

**Issue by mlongob** [phadej/binary-orphans#15]
It looks like the `0.1.4.0` version of this package was originally published without the change in #13. After #13, the package was re-published with the same version. This is a major issue for package maintainers. Going forward can you please bump up the Hackage version when publishing?

**Comment by phadej** [comment]
Why relaxing bounds is an issue?

**Comment by mlongob** [comment]
Now that I'm looking around, it looks like a pretty common occurrence for Hackage packages to relax bounds while not changing versions. I am having trouble managing a syncing tool to create Debian packages from Hackage packages. I'll have to explicitly add logic to handle this use case.

**Comment by phadej** [comment]
Cabal files inside Cabal packages downloaded from Hackage (with eg. `cabal get binary-orphans`) could have `x-revision` field:

```
% cat binary-orphans-0.1.4.0/binary-orphans.cabal| grep x-revision
x-revision: 6
```

If that additional revision would help you with your packaging

**Comment by mlongob** [comment]
That's exactly what I need. Thanks, Oleg.
