### ISSUE TITLE
Add instance for Natural

### ISSUE THREAD

**Issue by phadej** [phadej/binary-orphans#2]

**Comment by RyanGlScott** [comment]
Keep in mind that [this has been added](https://github.com/ekmett/nats/commit/f0b18711b1af7737d9d4bb96732b347f41b33d76) to the upstream `nats` repo.

**Comment by phadej** [comment]
@RyanGlScott ah, thanks for the info! Hackage docs are still build with 7.8.3, so it doesn't show up there :(

**Comment by RyanGlScott** [comment]
It's not your fault—it's an extremely recent commit to the `nats` GitHub repo which hasn't been uploaded to Hackage yet.

**Comment by phadej** [comment]
@RyanGlScott I mean it doesn't show up in `binary` documentation either, which is on Hackage already.
