### ISSUE TITLE
What is going on with the versions of binary-instances and binary-orphans?

### ISSUE THREAD

**Issue by colonelpanic8** [phadej/binary-orphans#40]
Something really strange is going on with the versions of these two hackage packages. Why do they both point at this repo, and why are the most recently published versions lower than previous versions?

**Comment by phadej** [comment]
Looks like I mixed up metadata for `binary-instances`. However changelogs exist
- https://hackage.haskell.org/package/binary-instances-1/changelog
- https://hackage.haskell.org/package/binary-orphans-1.0.1/changelog

and tell the story.
